1.Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

2.Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
a=[]
print("enter firts list")
for i in range(0,5):
    ele=int(input())
    a.append(ele)
print("enter the second list")
b=[]
for i in range(0,5):
    ele=int(input())
    b.append(ele)
print("two list are:")
print(a)
print(b)
import numpy as np
print("converted numpy array are")
arr1=np.array(a)
arr2=np.array(b)
print("first numoy array is")
print(arr1)
print("second numoy array is")
print(arr2)
c=np.concatenate((arr1, arr2), axis = 0) 
print("concatenate the two arrays")
print(c)
print("sorting numpy arrays") 
print("return type : ",c.sort())
print("sorting numpy arrays : ",c) 

enter firts list
1
247
5
7
4
enter the second list
4
7
5
8
6
two list are:
[1, 247, 5, 7, 4]
[4, 7, 5, 8, 6]
converted numpy array are
first numoy array is
[  1 247   5   7   4]
second numoy array is
[4 7 5 8 6]
concatenate the two arrays
[  1 247   5   7   4   4   7   5   8   6]
sorting numpy arrays
return type :  None
sorting numpy arrays :  [  1   4   4   5   5   6   7   7   8 247]


3.Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:

import numpy as np
 

arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 

print("Array is of type: ", type(arr))
 

print("No. of dimensions: ", arr.ndim)
 

print("Shape of array: ", arr.shape)
 

print("Size of array: ", arr.size)
 

print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


4.How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [12]:
import numpy as np 

arr=np.arange(4).reshape(2,2)
arr.shape
arr_2D=arr[np.newaxis]
arr_2D.shape

(1, 2, 2)

5.Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [2]:

import numpy as np 

arr1 = [1, -3, 15, -466] 
print ("Square Value of arr1 : \n", np.square(arr1)) 

arr2 = [1,2,3,4] 
print ("\nSquare Value of arr2 : ", np.square(arr2)) 
c=np.vstack((arr1,arr2))
print(c)
d=np.hstack((arr1,arr2))
print(d)


Square Value of arr1 : 
 [     1      9    225 217156]

Square Value of arr2 :  [ 1  4  9 16]
[[   1   -3   15 -466]
 [   1    2    3    4]]
[   1   -3   15 -466    1    2    3    4]


6.How to get unique items and counts of unique items?

In [3]:
# taking an input list 
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 

# taking an input list 
l1 = [] 

# taking an counter 
count = 0

# travesing the array 
for item in input_list: 
	if item not in l1: 
		count += 1
		l1.append(item) 

# printing the output 
print("No of unique items are:", count) 


No of unique items are: 5
